-- 0001 core schema
-- Every tenant-owned table carries org_id. Identifiers are UUIDs generated by clients (offline)
-- or the API. Valuation dates are DATE; instants are TIMESTAMPTZ (UTC). Money is integer cents.
-- Configuration (rule sets, templates) and nested evidence are versioned JSONB documents.

CREATE TABLE organisation (
  id          uuid PRIMARY KEY,
  name        text NOT NULL,
  abn         text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE app_user (
  id            uuid PRIMARY KEY,
  org_id        uuid NOT NULL REFERENCES organisation(id),
  email         text NOT NULL,
  display_name  text NOT NULL,
  -- external identity-provider subject (OIDC `sub`)
  idp_subject   text,
  credentials   jsonb NOT NULL DEFAULT '[]'::jsonb,
  status        text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'deleted')),
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX app_user_email_uq ON app_user (org_id, lower(email));
CREATE UNIQUE INDEX app_user_idp_uq ON app_user (idp_subject) WHERE idp_subject IS NOT NULL;

CREATE TABLE user_role (
  user_id  uuid NOT NULL REFERENCES app_user(id),
  role     text NOT NULL CHECK (role IN ('ADMINISTRATOR', 'STANDARDS_OWNER', 'ALLOCATOR', 'VALUER',
                                         'FIELD_INSPECTOR', 'QA_REVIEWER', 'FINANCE', 'CLIENT_READONLY')),
  PRIMARY KEY (user_id, role)
);

CREATE TABLE client (
  id          uuid PRIMARY KEY,
  org_id      uuid NOT NULL REFERENCES organisation(id),
  name        text NOT NULL,
  abn         text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE client_user (
  user_id    uuid NOT NULL REFERENCES app_user(id),
  client_id  uuid NOT NULL REFERENCES client(id),
  PRIMARY KEY (user_id, client_id)
);

-- Delivery is only permitted to recipients approved for the client.
CREATE TABLE approved_recipient (
  id           uuid PRIMARY KEY,
  org_id       uuid NOT NULL REFERENCES organisation(id),
  client_id    uuid NOT NULL REFERENCES client(id),
  email        text NOT NULL,
  approved_by  uuid NOT NULL REFERENCES app_user(id),
  approved_at  timestamptz NOT NULL,
  revoked_at   timestamptz
);
CREATE UNIQUE INDEX approved_recipient_uq ON approved_recipient (client_id, lower(email)) WHERE revoked_at IS NULL;

CREATE TABLE portfolio (
  id          uuid PRIMARY KEY,
  org_id      uuid NOT NULL REFERENCES organisation(id),
  client_id   uuid REFERENCES client(id),
  name        text NOT NULL,
  -- restricted portfolios are information barriers: membership required for every role
  restricted  boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE portfolio_member (
  portfolio_id  uuid NOT NULL REFERENCES portfolio(id),
  user_id       uuid NOT NULL REFERENCES app_user(id),
  PRIMARY KEY (portfolio_id, user_id)
);

CREATE TABLE data_source (
  id              text NOT NULL,
  org_id          uuid NOT NULL REFERENCES organisation(id),
  name            text NOT NULL,
  provider        text NOT NULL,
  kind            text NOT NULL,
  jurisdictions   text[] NOT NULL DEFAULT '{}',
  licence         jsonb NOT NULL,
  freshness_days  integer,
  status          text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'retired')),
  PRIMARY KEY (org_id, id)
);

-- ── Versioned configuration ────────────────────────────────────────────────────

CREATE TABLE rule_set_version (
  id              uuid PRIMARY KEY,
  org_id          uuid NOT NULL REFERENCES organisation(id),
  rule_set_id     text NOT NULL,
  version         text NOT NULL,
  status          text NOT NULL CHECK (status IN ('draft', 'in_review', 'approved', 'retired')),
  effective_from  date NOT NULL,
  effective_to    date,
  content         jsonb NOT NULL,
  content_hash    text NOT NULL,
  authored_by     text NOT NULL,
  approved_by     uuid REFERENCES app_user(id),
  approved_at     timestamptz,
  UNIQUE (org_id, rule_set_id, version)
);

CREATE TABLE template_version (
  id            uuid PRIMARY KEY,
  org_id        uuid NOT NULL REFERENCES organisation(id),
  template_id   text NOT NULL,
  version       integer NOT NULL,
  status        text NOT NULL CHECK (status IN ('draft', 'in_review', 'approved', 'retired')),
  content       jsonb NOT NULL,
  content_hash  text NOT NULL,
  authored_by   text NOT NULL,
  approved_by   uuid REFERENCES app_user(id),
  approved_at   timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, template_id, version)
);

-- ── Jobs and assets ────────────────────────────────────────────────────────────

CREATE TABLE job (
  id                      uuid PRIMARY KEY,
  org_id                  uuid NOT NULL REFERENCES organisation(id),
  reference               text NOT NULL,
  client_id               uuid NOT NULL REFERENCES client(id),
  portfolio_id            uuid REFERENCES portfolio(id),
  status                  text NOT NULL CHECK (status IN ('draft', 'active', 'submitted', 'in_review',
                                                          'returned', 'approved', 'issued', 'cancelled')),
  jurisdiction            text NOT NULL CHECK (jurisdiction IN ('NSW', 'VIC', 'QLD', 'WA', 'SA', 'TAS', 'ACT', 'NT')),
  purpose                 text NOT NULL CHECK (purpose IN ('MARKET_VALUE', 'CGT_RETROSPECTIVE', 'FAMILY_LAW',
                                                           'FINANCIAL_REPORTING', 'RENTAL_ASSESSMENT', 'INSURANCE_REPLACEMENT')),
  property_type           text NOT NULL CHECK (property_type IN ('VACANT_LAND', 'RESIDENTIAL', 'COMMERCIAL_OFFICE',
                                                                 'COMMERCIAL_RETAIL', 'INDUSTRIAL', 'SPECIALISED_MIXED_USE')),
  scope                   text NOT NULL CHECK (scope IN ('FULL', 'KERBSIDE', 'RESTRICTED', 'DESKTOP')),
  mode                    text NOT NULL CHECK (mode IN ('SINGLE', 'PORTFOLIO')),
  rule_set_version_id     uuid NOT NULL REFERENCES rule_set_version(id),
  template_version_id     uuid REFERENCES template_version(id),
  responsible_valuer_id   uuid REFERENCES app_user(id),
  reviewer_id             uuid REFERENCES app_user(id),
  fee_cents               integer CHECK (fee_cents IS NULL OR fee_cents >= 0),
  submitted_snapshot_hash text,
  approved_snapshot_hash  text,
  created_by              uuid NOT NULL REFERENCES app_user(id),
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),
  version                 integer NOT NULL DEFAULT 1,
  UNIQUE (org_id, reference)
);
CREATE INDEX job_org_status_idx ON job (org_id, status);

CREATE TABLE job_assignment (
  job_id   uuid NOT NULL REFERENCES job(id),
  user_id  uuid NOT NULL REFERENCES app_user(id),
  role     text NOT NULL CHECK (role IN ('inspector')),
  PRIMARY KEY (job_id, user_id, role)
);

CREATE TABLE asset (
  id                  uuid PRIMARY KEY,
  org_id              uuid NOT NULL REFERENCES organisation(id),
  job_id              uuid NOT NULL REFERENCES job(id),
  label               text NOT NULL,
  address             jsonb NOT NULL DEFAULT '{}'::jsonb,
  latitude            double precision CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
  longitude           double precision CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
  geocode_confidence  double precision,
  risk_level          text NOT NULL DEFAULT 'none' CHECK (risk_level IN ('none', 'low', 'medium', 'high')),
  version             integer NOT NULL DEFAULT 1,
  field_versions      jsonb NOT NULL DEFAULT '{}'::jsonb,
  deleted             boolean NOT NULL DEFAULT false,
  created_by          uuid NOT NULL REFERENCES app_user(id),
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX asset_job_idx ON asset (job_id);

-- Captured values for configuration-driven fields, with provenance. Current value per
-- (job, asset, field); every change is also appended to field_value_history.
CREATE TABLE field_value (
  id          uuid PRIMARY KEY,
  org_id      uuid NOT NULL REFERENCES organisation(id),
  job_id      uuid NOT NULL REFERENCES job(id),
  asset_id    uuid REFERENCES asset(id),
  field_id    text NOT NULL,
  value       jsonb NOT NULL,
  provenance  jsonb NOT NULL,
  version     integer NOT NULL DEFAULT 1,
  updated_by  uuid NOT NULL REFERENCES app_user(id),
  updated_at  timestamptz NOT NULL
);
CREATE UNIQUE INDEX field_value_uq ON field_value (job_id, coalesce(asset_id, '00000000-0000-0000-0000-000000000000'::uuid), field_id);

CREATE TABLE field_value_history (
  id              bigserial PRIMARY KEY,
  field_value_id  uuid NOT NULL REFERENCES field_value(id),
  version         integer NOT NULL,
  value           jsonb NOT NULL,
  provenance      jsonb NOT NULL,
  changed_by      uuid NOT NULL REFERENCES app_user(id),
  changed_at      timestamptz NOT NULL,
  reason          text
);

CREATE TABLE document (
  id           uuid PRIMARY KEY,
  org_id       uuid NOT NULL REFERENCES organisation(id),
  job_id       uuid REFERENCES job(id),
  kind         text NOT NULL,
  filename     text NOT NULL,
  sha256       text NOT NULL,
  size_bytes   integer NOT NULL,
  storage_key  text NOT NULL,
  uploaded_by  uuid NOT NULL REFERENCES app_user(id),
  uploaded_at  timestamptz NOT NULL
);

-- ── Evidence and analysis ──────────────────────────────────────────────────────

CREATE TABLE sale_comparable (
  id          uuid PRIMARY KEY,
  org_id      uuid NOT NULL REFERENCES organisation(id),
  job_id      uuid NOT NULL REFERENCES job(id),
  asset_id    uuid NOT NULL REFERENCES asset(id),
  data        jsonb NOT NULL,
  created_by  uuid NOT NULL REFERENCES app_user(id),
  created_at  timestamptz NOT NULL
);

CREATE TABLE rental_comparable (
  id          uuid PRIMARY KEY,
  org_id      uuid NOT NULL REFERENCES organisation(id),
  job_id      uuid NOT NULL REFERENCES job(id),
  asset_id    uuid NOT NULL REFERENCES asset(id),
  data        jsonb NOT NULL,
  created_by  uuid NOT NULL REFERENCES app_user(id),
  created_at  timestamptz NOT NULL
);

CREATE TABLE calculation (
  id               text PRIMARY KEY,
  org_id           uuid NOT NULL REFERENCES organisation(id),
  job_id           uuid NOT NULL REFERENCES job(id),
  asset_id         uuid REFERENCES asset(id),
  sale_id          uuid REFERENCES sale_comparable(id),
  formula_id       text NOT NULL,
  formula_version  integer NOT NULL,
  record           jsonb NOT NULL,
  trace_hash       text NOT NULL,
  created_at       timestamptz NOT NULL
);
CREATE INDEX calculation_job_idx ON calculation (job_id);

CREATE TABLE market_commentary (
  id          uuid PRIMARY KEY,
  org_id      uuid NOT NULL REFERENCES organisation(id),
  job_id      uuid NOT NULL REFERENCES job(id),
  asset_id    uuid REFERENCES asset(id),
  level       text NOT NULL CHECK (level IN ('national', 'state', 'local')),
  as_at_date  date NOT NULL,
  data        jsonb NOT NULL
);

CREATE TABLE risk_flag (
  id        uuid PRIMARY KEY,
  org_id    uuid NOT NULL REFERENCES organisation(id),
  job_id    uuid NOT NULL REFERENCES job(id),
  asset_id  uuid REFERENCES asset(id),
  status    text NOT NULL CHECK (status IN ('open', 'resolved', 'accepted')),
  data      jsonb NOT NULL
);

CREATE TABLE photo (
  id              uuid PRIMARY KEY,
  org_id          uuid NOT NULL REFERENCES organisation(id),
  job_id          uuid NOT NULL REFERENCES job(id),
  asset_id        uuid NOT NULL REFERENCES asset(id),
  sha256          text NOT NULL,
  data            jsonb NOT NULL,
  version         integer NOT NULL DEFAULT 1,
  field_versions  jsonb NOT NULL DEFAULT '{}'::jsonb,
  deleted         boolean NOT NULL DEFAULT false,
  created_at      timestamptz NOT NULL
);
-- the same image cannot be stored twice for an asset (offline replay de-duplication)
CREATE UNIQUE INDEX photo_asset_sha_uq ON photo (asset_id, sha256) WHERE NOT deleted;

CREATE TABLE ai_suggestion (
  id        uuid PRIMARY KEY,
  org_id    uuid NOT NULL REFERENCES organisation(id),
  job_id    uuid NOT NULL REFERENCES job(id),
  asset_id  uuid NOT NULL REFERENCES asset(id),
  status    text NOT NULL CHECK (status IN ('pending', 'accepted', 'edited', 'rejected')),
  data      jsonb NOT NULL
);

CREATE TABLE accepted_fact (
  id             uuid PRIMARY KEY,
  org_id         uuid NOT NULL REFERENCES organisation(id),
  job_id         uuid NOT NULL REFERENCES job(id),
  asset_id       uuid NOT NULL REFERENCES asset(id),
  suggestion_id  uuid NOT NULL REFERENCES ai_suggestion(id),
  data           jsonb NOT NULL
);

-- ── Areas and sketches ─────────────────────────────────────────────────────────

CREATE TABLE sketch_version (
  id            uuid PRIMARY KEY,
  org_id        uuid NOT NULL REFERENCES organisation(id),
  job_id        uuid NOT NULL REFERENCES job(id),
  asset_id      uuid NOT NULL REFERENCES asset(id),
  sketch_id     uuid NOT NULL,
  version       integer NOT NULL,
  status        text NOT NULL CHECK (status IN ('working', 'approved', 'frozen')),
  data          jsonb NOT NULL,
  content_hash  text NOT NULL,
  created_by    uuid NOT NULL REFERENCES app_user(id),
  created_at    timestamptz NOT NULL,
  UNIQUE (sketch_id, version)
);

CREATE TABLE measurement_approval (
  id                 uuid PRIMARY KEY,
  org_id             uuid NOT NULL REFERENCES organisation(id),
  job_id             uuid NOT NULL REFERENCES job(id),
  sketch_version_id  uuid NOT NULL REFERENCES sketch_version(id),
  schedule           jsonb NOT NULL,
  schedule_hash      text NOT NULL,
  approved_by        uuid NOT NULL REFERENCES app_user(id),
  approved_at        timestamptz NOT NULL
);

-- ── Validation, certification and QA ───────────────────────────────────────────

CREATE TABLE validation_acknowledgement (
  id       uuid PRIMARY KEY,
  org_id   uuid NOT NULL REFERENCES organisation(id),
  job_id   uuid NOT NULL REFERENCES job(id),
  code     text NOT NULL,
  path     text NOT NULL,
  reason   text NOT NULL,
  ack_by   uuid NOT NULL REFERENCES app_user(id),
  ack_at   timestamptz NOT NULL,
  UNIQUE (job_id, code, path)
);

CREATE TABLE validation_run (
  id         uuid PRIMARY KEY,
  org_id     uuid NOT NULL REFERENCES organisation(id),
  job_id     uuid NOT NULL REFERENCES job(id),
  stage      text NOT NULL,
  result     jsonb NOT NULL,
  ran_by     uuid NOT NULL REFERENCES app_user(id),
  ran_at     timestamptz NOT NULL
);

CREATE TABLE certification (
  id             uuid PRIMARY KEY,
  org_id         uuid NOT NULL REFERENCES organisation(id),
  job_id         uuid NOT NULL REFERENCES job(id),
  data           jsonb NOT NULL,
  snapshot_hash  text NOT NULL,
  signed_by      uuid NOT NULL REFERENCES app_user(id),
  signed_at      timestamptz NOT NULL
);

CREATE TABLE qa_review (
  id                       uuid PRIMARY KEY,
  org_id                   uuid NOT NULL REFERENCES organisation(id),
  job_id                   uuid NOT NULL REFERENCES job(id),
  reviewer_id              uuid NOT NULL REFERENCES app_user(id),
  reviewed_snapshot_hash   text NOT NULL,
  outcome                  text CHECK (outcome IN ('approved', 'returned')),
  data                     jsonb NOT NULL,
  started_at               timestamptz NOT NULL,
  completed_at             timestamptz
);

CREATE TABLE self_approval_exception (
  id             uuid PRIMARY KEY,
  org_id         uuid NOT NULL REFERENCES organisation(id),
  job_id         uuid NOT NULL REFERENCES job(id),
  authorised_by  uuid NOT NULL REFERENCES app_user(id),
  reason         text NOT NULL,
  authorised_at  timestamptz NOT NULL
);

-- ── Issue: reports, invoices, delivery ─────────────────────────────────────────

CREATE TABLE report (
  id                   uuid PRIMARY KEY,
  org_id               uuid NOT NULL REFERENCES organisation(id),
  job_id               uuid NOT NULL REFERENCES job(id),
  version              integer NOT NULL,
  status               text NOT NULL CHECK (status IN ('issued', 'superseded')),
  -- complete, canonical issue snapshot: everything needed to re-render PDF, invoice and email
  snapshot             jsonb NOT NULL,
  snapshot_hash        text NOT NULL,
  pdf                  bytea NOT NULL,
  pdf_sha256           text NOT NULL,
  template_version_id  uuid NOT NULL REFERENCES template_version(id),
  issued_by            uuid NOT NULL REFERENCES app_user(id),
  issued_at            timestamptz NOT NULL,
  UNIQUE (job_id, version)
);

CREATE TABLE invoice (
  id             uuid PRIMARY KEY,
  org_id         uuid NOT NULL REFERENCES organisation(id),
  job_id         uuid NOT NULL REFERENCES job(id),
  report_id      uuid NOT NULL REFERENCES report(id),
  number         text NOT NULL,
  data           jsonb NOT NULL,
  subtotal_cents integer NOT NULL,
  gst_cents      integer NOT NULL,
  total_cents    integer NOT NULL,
  pdf            bytea NOT NULL,
  pdf_sha256     text NOT NULL,
  issued_at      timestamptz NOT NULL,
  UNIQUE (org_id, number)
);

CREATE TABLE email_delivery (
  id                   uuid PRIMARY KEY,
  org_id               uuid NOT NULL REFERENCES organisation(id),
  job_id               uuid NOT NULL REFERENCES job(id),
  report_id            uuid NOT NULL REFERENCES report(id),
  recipient            text NOT NULL,
  payload_hash         text NOT NULL,
  status               text NOT NULL CHECK (status IN ('queued', 'sent', 'delivered', 'bounced', 'failed')),
  provider_message_id  text,
  attempts             integer NOT NULL DEFAULT 0,
  created_at           timestamptz NOT NULL,
  updated_at           timestamptz NOT NULL
);

-- ── Audit, sync, retention ─────────────────────────────────────────────────────

CREATE TABLE audit_event (
  id           uuid PRIMARY KEY,
  org_id       uuid NOT NULL REFERENCES organisation(id),
  stream_id    text NOT NULL,
  seq          integer NOT NULL,
  at           timestamptz NOT NULL,
  -- the hashed event exactly as created (canonical JSON source of truth for verification)
  event        jsonb NOT NULL,
  action       text NOT NULL,
  entity_type  text NOT NULL,
  entity_id    text NOT NULL,
  actor_id     text NOT NULL,
  prev_hash    text NOT NULL,
  hash         text NOT NULL,
  UNIQUE (stream_id, seq)
);
CREATE INDEX audit_event_entity_idx ON audit_event (entity_type, entity_id);

CREATE TABLE sync_operation (
  op_id        text PRIMARY KEY,
  org_id       uuid NOT NULL REFERENCES organisation(id),
  device_id    text NOT NULL,
  user_id      uuid NOT NULL REFERENCES app_user(id),
  entity_type  text NOT NULL,
  entity_id    text NOT NULL,
  outcome      text NOT NULL,
  received_at  timestamptz NOT NULL
);

CREATE TABLE sync_conflict (
  id           uuid PRIMARY KEY,
  org_id       uuid NOT NULL REFERENCES organisation(id),
  op_id        text NOT NULL,
  entity_type  text NOT NULL,
  entity_id    text NOT NULL,
  conflicts    jsonb NOT NULL,
  status       text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved')),
  created_at   timestamptz NOT NULL
);

CREATE TABLE legal_hold (
  id           uuid PRIMARY KEY,
  org_id       uuid NOT NULL REFERENCES organisation(id),
  scope_type   text NOT NULL CHECK (scope_type IN ('job', 'client', 'portfolio')),
  scope_id     uuid NOT NULL,
  reason       text NOT NULL,
  applied_by   uuid NOT NULL REFERENCES app_user(id),
  applied_at   timestamptz NOT NULL,
  released_by  uuid REFERENCES app_user(id),
  released_at  timestamptz
);
