-- 0003 atomic invoice numbering and tenant-scoped sync idempotency

-- Invoice numbers come from a per-organisation, per-year counter incremented atomically
-- (INSERT … ON CONFLICT DO UPDATE … RETURNING), so concurrent issues never collide.
CREATE TABLE invoice_counter (
  org_id       uuid NOT NULL REFERENCES organisation(id),
  year         integer NOT NULL,
  last_number  integer NOT NULL,
  PRIMARY KEY (org_id, year)
);

-- Operation ids are generated by devices; scope idempotency to the organisation and device so an
-- id used elsewhere can never cause a legitimate operation to be dropped as a duplicate.
ALTER TABLE sync_operation DROP CONSTRAINT sync_operation_pkey;
ALTER TABLE sync_operation ADD PRIMARY KEY (org_id, device_id, op_id);
