/**
 * Generates the specification tables in docs/spec/generated/ from the code that enforces them,
 * so the documentation cannot drift from the implementation. Run `pnpm docs:generate`;
 * CI runs `pnpm docs:check` and fails if the committed files are stale.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  AU_CORE_RULE_SET,
  DEFAULT_CONVENTIONS,
  FIELD_CATALOGUE,
  FORMULAS,
  INSPECTION_SCOPES,
  JURISDICTIONS,
  PERMISSIONS,
  PROPERTY_TYPES,
  PROPERTY_TYPE_LABELS,
  REPORT_PURPOSES,
  REPORT_PURPOSE_LABELS,
  ROLES,
  ROLE_PERMISSIONS,
  HUMAN_ONLY_PERMISSIONS,
  MFA_PERMISSIONS,
  ORG_WIDE_ROLES,
  SEED_CLAUSES,
  TRANSITIONS,
  resolveRequirements,
  validationCatalogue,
  type JobSelection,
  type RuleCondition,
} from '@vp/domain';
import { buildApp } from '../src/app.js';
import { loadConfig } from '../src/config.js';
import { PgliteDb } from '../src/db/db.js';

const OUT = fileURLToPath(new URL('../../../docs/spec/generated/', import.meta.url));
const HEADER = (title: string) =>
  `# ${title}\n\n> Generated by \`pnpm docs:generate\` from the code that enforces it. Do not edit by hand.\n\n`;
const esc = (s: string) => s.replaceAll('|', '\\|').replaceAll('\n', ' ');
const table = (head: string[], rows: string[][]) =>
  [
    `| ${head.join(' | ')} |`,
    `| ${head.map(() => '---').join(' | ')} |`,
    ...rows.map((r) => `| ${r.map(esc).join(' | ')} |`),
  ].join('\n') + '\n';

function describeWhen(w: RuleCondition): string {
  const parts: string[] = [];
  if (w.purposes) parts.push(`purpose ∈ {${w.purposes.join(', ')}}`);
  if (w.propertyTypes) parts.push(`type ∈ {${w.propertyTypes.join(', ')}}`);
  if (w.scopes) parts.push(`scope ∈ {${w.scopes.join(', ')}}`);
  if (w.jurisdictions) parts.push(`jurisdiction ∈ {${w.jurisdictions.join(', ')}}`);
  if (w.modes) parts.push(`mode ∈ {${w.modes.join(', ')}}`);
  for (const f of w.fields ?? []) {
    const cond =
      f.equals !== undefined
        ? `= ${String(f.equals)}`
        : f.in
          ? `∈ {${f.in.join(', ')}}`
          : f.includes
            ? `includes ${f.includes}`
            : f.present !== undefined
              ? f.present
                ? 'is present'
                : 'is empty'
              : 'has a value';
    parts.push(`\`${f.fieldId}\` ${cond}`);
  }
  return parts.length ? parts.join('; ') : 'always';
}

function fieldCatalogue(): string {
  return (
    HEADER('Field catalogue') +
    `${FIELD_CATALOGUE.length} fields. \`job\` fields are captured once per job; \`asset\` fields once per asset. ` +
    'Personal-information fields are masked in logs and restricted in exports. Review tags mark wording that needs specialist sign-off.\n\n' +
    table(
      ['Field id', 'Label', 'Section', 'Level', 'Type', 'Options / unit', 'Personal', 'Review'],
      FIELD_CATALOGUE.map((f) => [
        `\`${f.id}\``,
        f.label,
        f.section,
        f.level,
        f.type,
        f.options?.join(', ') ?? f.unit ?? '',
        f.personal ? 'yes' : '',
        f.review ? `[REVIEW: ${f.review}]` : '',
      ]),
    )
  );
}

function requirementRules(): string {
  let out = HEADER(
    `Requirement rules — ${AU_CORE_RULE_SET.id} ${AU_CORE_RULE_SET.version} (${AU_CORE_RULE_SET.status})`,
  );
  out += `${AU_CORE_RULE_SET.notes}\n\n## Requirement rules\n\n`;
  out += table(
    [
      'Rule',
      'Description',
      'Applies when',
      'Requires',
      'Recommends',
      'Sections',
      'Warnings',
      'Specialist review',
    ],
    AU_CORE_RULE_SET.rules.map((r) => [
      r.id,
      r.description,
      describeWhen(r.when),
      (r.require ?? []).map((f) => `\`${f}\``).join(', '),
      (r.recommend ?? []).map((f) => `\`${f}\``).join(', '),
      (r.sections ?? []).join(', '),
      (r.warnings ?? []).map((w) => `${w.code}: ${w.message}`).join(' '),
      (r.specialistReview ?? []).join(', '),
    ]),
  );
  out += '\n## Selection rules\n\n';
  out += table(
    ['Rule', 'Applies when', 'Severity', 'Message', 'Review'],
    AU_CORE_RULE_SET.selectionRules.map((r) => [
      r.id,
      describeWhen(r.when),
      r.severity,
      r.message,
      r.review ?? '',
    ]),
  );
  return out;
}

function matrix(): string {
  const base = (
    purpose: JobSelection['purpose'],
    propertyType: JobSelection['propertyType'],
    scope: JobSelection['scope'] = 'FULL',
    jurisdiction: JobSelection['jurisdiction'] = 'VIC',
    mode: JobSelection['mode'] = 'SINGLE',
  ): JobSelection => ({
    purpose,
    propertyType,
    scope,
    jurisdiction,
    mode,
  });
  const req = (s: JobSelection) =>
    new Set(
      resolveRequirements(s, AU_CORE_RULE_SET)
        .fields.filter((f) => f.level === 'required')
        .map((f) => f.fieldId),
    );
  const rec = (s: JobSelection) =>
    new Set(
      resolveRequirements(s, AU_CORE_RULE_SET)
        .fields.filter((f) => f.level === 'recommended')
        .map((f) => f.fieldId),
    );

  let out = HEADER('Report purpose × property type × inspection scope field matrix');
  out +=
    'Resolved by `resolveRequirements` from the draft AU core rule set. Conditional requirements that depend on captured values ' +
    '(e.g. leased occupancy, DCF selected, disclosed conflict) are listed in the rule table and are not shown here. ' +
    'Combinations marked ⛔ are blocked by a selection rule.\n\n';

  out += '## 1. Required-field counts (scope FULL, VIC, single asset)\n\n';
  out += table(
    ['Purpose \\ Property type', ...PROPERTY_TYPES.map((t) => PROPERTY_TYPE_LABELS[t])],
    REPORT_PURPOSES.map((p) => [
      REPORT_PURPOSE_LABELS[p],
      ...PROPERTY_TYPES.map((t) => {
        const r = resolveRequirements(base(p, t), AU_CORE_RULE_SET);
        const blocked = r.selectionIssues.some((i) => i.severity === 'blocking');
        return blocked ? '⛔' : `${r.fields.filter((f) => f.level === 'required').length}`;
      }),
    ]),
  );

  out += '\n## 2. Fields by purpose and property type (scope FULL, VIC)\n\n';
  out +=
    'Legend: **R** required, r recommended, blank not applicable. Base fields required for every job are listed once in §4.\n\n';
  const baseline = req(base('MARKET_VALUE', 'VACANT_LAND', 'DESKTOP'));
  const common = new Set(
    [...baseline].filter((f) =>
      REPORT_PURPOSES.every((p) => PROPERTY_TYPES.every((t) => req(base(p, t, 'DESKTOP')).has(f))),
    ),
  );
  for (const p of REPORT_PURPOSES) {
    const selections = PROPERTY_TYPES.map((t) => base(p, t));
    const reqSets = selections.map(req);
    const recSets = selections.map(rec);
    const fields = [
      ...new Set([...reqSets.flatMap((s) => [...s]), ...recSets.flatMap((s) => [...s])]),
    ]
      .filter((f) => !common.has(f))
      .filter((f) => !['dates.inspection', 'scope.areasInspected'].includes(f))
      .sort();
    out += `### ${REPORT_PURPOSE_LABELS[p]} (\`${p}\`)\n\n`;
    out += table(
      ['Field', ...PROPERTY_TYPES.map((t) => PROPERTY_TYPE_LABELS[t])],
      fields.map((f) => [
        `\`${f}\``,
        ...PROPERTY_TYPES.map((_, i) =>
          reqSets[i]?.has(f) ? '**R**' : recSets[i]?.has(f) ? 'r' : '',
        ),
      ]),
    );
    out += '\n';
  }

  out += '## 3. Inspection-scope deltas (market value, residential, VIC)\n\n';
  const full = req(base('MARKET_VALUE', 'RESIDENTIAL', 'FULL'));
  out += table(
    ['Scope', 'Adds (vs FULL)', 'Removes (vs FULL)', 'Sections added'],
    INSPECTION_SCOPES.map((sc) => {
      const s = req(base('MARKET_VALUE', 'RESIDENTIAL', sc));
      const sections = resolveRequirements(
        base('MARKET_VALUE', 'RESIDENTIAL', sc),
        AU_CORE_RULE_SET,
      ).sections;
      const fullSections = resolveRequirements(
        base('MARKET_VALUE', 'RESIDENTIAL', 'FULL'),
        AU_CORE_RULE_SET,
      ).sections;
      return [
        sc,
        [...s]
          .filter((f) => !full.has(f))
          .map((f) => `\`${f}\``)
          .join(', '),
        [...full]
          .filter((f) => !s.has(f))
          .map((f) => `\`${f}\``)
          .join(', '),
        sections.filter((x) => !fullSections.includes(x)).join(', '),
      ];
    }),
  );

  out += '\n## 4. Fields required for every job\n\n';
  out +=
    [...common]
      .sort()
      .map((f) => `- \`${f}\``)
      .join('\n') + '\n';

  out += '\n## 5. Jurisdiction and mode deltas (market value, residential, FULL)\n\n';
  const vic = resolveRequirements(base('MARKET_VALUE', 'RESIDENTIAL'), AU_CORE_RULE_SET);
  out += table(
    ['Selection', 'Additional recommended fields', 'Selection warnings'],
    [
      ...JURISDICTIONS.map((j) => {
        const r = resolveRequirements(
          base('MARKET_VALUE', 'RESIDENTIAL', 'FULL', j),
          AU_CORE_RULE_SET,
        );
        const generic = resolveRequirements(
          base('MARKET_VALUE', 'RESIDENTIAL', 'FULL', 'SA'),
          AU_CORE_RULE_SET,
        );
        const extra = r.fields
          .filter((f) => !generic.fields.some((g) => g.fieldId === f.fieldId))
          .map((f) => `\`${f.fieldId}\``);
        return [j, extra.join(', '), r.selectionIssues.map((i) => i.ruleId).join(', ')];
      }),
      [
        'PORTFOLIO mode',
        resolveRequirements(
          base('MARKET_VALUE', 'RESIDENTIAL', 'FULL', 'VIC', 'PORTFOLIO'),
          AU_CORE_RULE_SET,
        )
          .fields.filter((f) => !vic.fields.some((g) => g.fieldId === f.fieldId))
          .map((f) => `\`${f.fieldId}\` (${f.level})`)
          .join(', '),
        '',
      ],
    ],
  );
  return out;
}

function permissions(): string {
  let out = HEADER('Permission matrix');
  out +=
    `Organisation-wide roles: ${[...ORG_WIDE_ROLES].join(', ')}. Other roles act only on jobs they are assigned to or whose portfolio they belong to. ` +
    'Restricted portfolios require membership for every role. 👤 = human actor only; 🔐 = MFA required.\n\n';
  out += table(
    ['Permission', ...ROLES, 'Human only', 'MFA'],
    PERMISSIONS.map((p) => [
      `\`${p}\``,
      ...ROLES.map((r) => (ROLE_PERMISSIONS[r].includes(p) ? '✓' : '')),
      HUMAN_ONLY_PERMISSIONS.has(p) ? '👤' : '',
      MFA_PERMISSIONS.has(p) ? '🔐' : '',
    ]),
  );
  out += '\n## Workflow transitions\n\n';
  out += table(
    ['Action', 'From', 'To', 'Permission', 'Audit action'],
    Object.entries(TRANSITIONS).map(([a, t]) => [
      a,
      t.from.join(', '),
      t.to,
      `\`${t.permission}\``,
      `\`${t.auditAction}\``,
    ]),
  );
  return out;
}

function validation(): string {
  const rules = validationCatalogue();
  let out = HEADER('Validation rules catalogue');
  out += `${rules.length} rules. Blocking findings must be resolved; warnings may be acknowledged with a reason (recorded and audited). Stages: draft (while capturing), submit (QA submission), issue (final issue).\n\n`;
  out += table(
    ['Code', 'Title', 'Category', 'Severity', 'Stages', 'Acknowledgeable', 'Description', 'Review'],
    rules.map((r) => [
      r.code,
      r.title,
      r.category,
      r.severity,
      r.stages.join(', '),
      r.acknowledgeable ? 'yes' : 'no',
      r.description,
      r.review ? `[REVIEW: ${r.review}]` : '',
    ]),
  );
  return out;
}

function formulasAndConventions(): string {
  let out = HEADER('Formula registry, measurement conventions and clause library');
  out +=
    '## Formulas\n\nEvery calculation records formula id, version, inputs with units and source references, and output; versions are immutable.\n\n';
  out += table(
    ['Formula', 'Version', 'Title', 'Expression', 'Inputs', 'Output', 'Review'],
    FORMULAS.map((f) => [
      `\`${f.id}\``,
      String(f.version),
      f.title,
      f.expression,
      f.inputs
        .map(
          (i) =>
            `${i.name}${i.repeated ? '[]' : ''} (${i.unit}${i.optional ? ', optional' : ''}${i.default !== undefined ? `, default ${i.default}` : ''})`,
        )
        .join('; '),
      `${f.output.unit}, ${f.output.dp} dp`,
      f.review ? `[REVIEW: ${f.review}]` : '',
    ]),
  );
  out += '\n## Measurement conventions (draft)\n\n';
  out += table(
    ['Id', 'Name', 'Basis', 'Included component types', 'Reference', 'Status'],
    DEFAULT_CONVENTIONS.map((c) => [
      `\`${c.id}\``,
      c.name,
      c.basis,
      c.includes.join(', '),
      c.reference,
      `${c.status} [REVIEW: ${c.review}]`,
    ]),
  );
  out +=
    '\n## Clause library seed\n\nAll seed clauses are placeholders; firm-authored wording must be approved before issue.\n\n';
  out += table(
    ['Clause', 'Title', 'Status', 'Reviewers'],
    SEED_CLAUSES.map((c) => [
      `\`${c.clauseId}\``,
      c.title,
      c.status,
      c.review.map((r) => `[REVIEW: ${r}]`).join(' '),
    ]),
  );
  return out;
}

async function openApi(): Promise<string> {
  const db = await PgliteDb.create();
  try {
    const { router, app } = await buildApp({ config: loadConfig({ NODE_ENV: 'test' }), db });
    const doc = router.openApi();
    await app.close();
    return `${JSON.stringify(doc, null, 2)}\n`;
  } finally {
    await db.close();
  }
}

async function endpointTable(spec: string): Promise<string> {
  type Op = {
    summary: string;
    tags: string[];
    'x-permission'?: string;
    'x-actors'?: string[];
    security?: unknown[];
  };
  const doc = JSON.parse(spec) as { paths: Record<string, Record<string, Op>> };
  const rows: string[][] = [];
  for (const [path, ops] of Object.entries(doc.paths)) {
    for (const [method, op] of Object.entries(ops)) {
      const access = op['x-permission']
        ? `\`${op['x-permission']}\``
        : op.security?.length === 0
          ? 'public'
          : 'authenticated';
      const actors =
        op['x-actors'] && op['x-actors'].join(',') !== 'human'
          ? ` — ${op['x-actors'].join(', ')} actors only`
          : '';
      rows.push([
        op.tags.join(', '),
        method.toUpperCase(),
        `\`${path}\``,
        access + actors,
        op.summary,
      ]);
    }
  }
  rows.sort(
    (a, b) => (a[0] ?? '').localeCompare(b[0] ?? '') || (a[2] ?? '').localeCompare(b[2] ?? ''),
  );
  return Promise.resolve(
    HEADER('API endpoints') + table(['Area', 'Method', 'Path', 'Permission', 'Summary'], rows),
  );
}

await mkdir(OUT, { recursive: true });
const spec = await openApi();
const files: [string, string][] = [
  ['field-catalogue.md', fieldCatalogue()],
  ['requirement-rules.md', requirementRules()],
  ['field-matrix.md', matrix()],
  ['permission-matrix.md', permissions()],
  ['validation-catalogue.md', validation()],
  ['formulas-conventions-clauses.md', formulasAndConventions()],
  ['openapi.json', spec],
  ['api-endpoints.md', await endpointTable(spec)],
];
for (const [name, content] of files) await writeFile(join(OUT, name), content);

// Embed the permission matrix in section 02 between markers (kept in sync by docs:check).
const personas = fileURLToPath(
  new URL('../../../docs/spec/02-personas-and-permissions.md', import.meta.url),
);
const doc = await readFile(personas, 'utf8');
const start = '<!-- PERMISSION-MATRIX:START -->';
const end = '<!-- PERMISSION-MATRIX:END -->';
if (doc.includes(start) && doc.includes(end)) {
  const body = permissions()
    .split('\n')
    .slice(4)
    .join('\n')
    .replaceAll(/^# /gm, '### ')
    .replaceAll(/^## /gm, '### ');
  await writeFile(
    personas,
    `${doc.slice(0, doc.indexOf(start) + start.length)}\n\n${body.trim()}\n\n${doc.slice(doc.indexOf(end))}`,
  );
}
process.stdout.write(`generated ${files.length} files in docs/spec/generated\n`);
