export const ROLES = [
  'ADMINISTRATOR',
  'STANDARDS_OWNER',
  'ALLOCATOR',
  'VALUER',
  'FIELD_INSPECTOR',
  'QA_REVIEWER',
  'FINANCE',
  'CLIENT_READONLY',
] as const;
export type Role = (typeof ROLES)[number];

export const ROLE_LABELS: Readonly<Record<Role, string>> = {
  ADMINISTRATOR: 'Administrator',
  STANDARDS_OWNER: 'Standards owner',
  ALLOCATOR: 'Allocator',
  VALUER: 'Valuer',
  FIELD_INSPECTOR: 'Field inspector',
  QA_REVIEWER: 'QA reviewer',
  FINANCE: 'Finance',
  CLIENT_READONLY: 'Client (read-only)',
};

export const PERMISSIONS = [
  'org.manage',
  'user.manage',
  'datasource.manage',
  'template.edit',
  'template.approve',
  'ruleset.edit',
  'ruleset.approve',
  'job.create',
  'job.read',
  'job.update',
  'job.allocate',
  'job.cancel',
  'engagement.accept',
  'asset.edit',
  'inspection.capture',
  'photo.capture',
  'photo.redact',
  'photo.view_unredacted',
  'evidence.edit',
  'valuation.edit',
  'calculation.run',
  'calculation.override',
  'sketch.edit',
  'measurement.approve',
  'ai.decide',
  'validation.acknowledge',
  'certification.sign',
  'qa.review',
  'qa.approve',
  'qa.self_approval_exception',
  'report.generate_draft',
  'report.issue',
  'report.read_issued',
  'invoice.manage',
  'invoice.read',
  'email.send',
  'audit.read',
  'legal_hold.manage',
  'retention.manage',
] as const;
export type Permission = (typeof PERMISSIONS)[number];
